server:
  port: 8080
  servlet:
    context-path: /
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


  datasource:
    url: jdbc:mariadb://localhost:3306/bms_test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MariaDB53Dialect