CREATE TABLE `m_score` (
	`num` INT(11) NOT NULL,
	`title` VARCHAR(100) NOT NULL,
	`score` INT(11) NOT NULL,
	`NAME` VARCHAR(20) NOT NULL,
	`NAME2` VARCHAR(20) NULL DEFAULT NULL,
	PRIMARY KEY (`num`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


CREATE DEFINER=`root`@`localhost` PROCEDURE `setName2`()
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN
	UPDATE m_score SET NAME2 = concat(SUBSTRING(NAME,1,3),'*****') WHERE NAME2 IS NULL;
END